"""Forth migration. Create users, bookings, rooms.

Revision ID: 3a3311600686
Revises: 3453e57206f4
Create Date: 2023-11-07 20:36:10.940628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3311600686'
down_revision: Union[str, None] = '3453e57206f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
