"""Second migration. Create users, bookings, rooms.

Revision ID: e106ee0de7e0
Revises: e5bb8dd3ef4f
Create Date: 2023-10-13 00:17:43.517353

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e106ee0de7e0'
down_revision: Union[str, None] = 'e5bb8dd3ef4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
